# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-07-18T00:31:27+00:00

from __future__ import annotations

from typing import Optional

from fastapi import FastAPI

from .models import Task, TasksNamePutRequest, TasksPostRequest, UsersNamePostResponse

app = FastAPI(
    title='Supervisor Server API',
    version='1.0',
)


@app.post('/tasks', response_model=None)
def run_create_task(id: str, key: str = ..., body: TasksPostRequest = ...) -> None:
    """
    Create a new task
    """
    pass


@app.get('/tasks', response_model=None)
def run_read_tasks(
    search: Optional[str] = None,
    limit: Optional[int] = None,
    offset: Optional[int] = None,
) -> None:
    """
    Get all tasks
    """
    pass


@app.get('/tasks/{name}', response_model=Task)
def run_read_task(name: str) -> Task:
    """
    Get information about a task
    """
    pass


@app.put('/tasks/{name}', response_model=None)
def run_update_task(
    id: str, key: str = ..., name: str = ..., body: TasksNamePutRequest = ...
) -> None:
    """
    Update data of a task
    """
    pass


@app.delete('/tasks/{name}', response_model=None)
def run_delete_task(id: str, key: str = ..., name: str = ...) -> None:
    """
    Delete a task
    """
    pass


@app.get('/tasks/{name}/queue', response_model=None)
def run_read_queue(
    name: str, start: Optional[int] = None, end: Optional[int] = None
) -> None:
    """
    Get IDs of the queue of a task
    """
    pass


@app.put('/tasks/{name}/queue', response_model=None)
def run_join_queue(id: str, key: str = ..., name: str = ...) -> None:
    """
    Join the queue
    """
    pass


@app.delete('/tasks/{name}/queue', response_model=None)
def run_leave_queue(id: str, key: str = ..., name: str = ...) -> None:
    """
    Dequeue yourself from the queue
    """
    pass


@app.post('/users/{name}', response_model=UsersNamePostResponse)
def run_create_user(name: str, link: Optional[str] = None) -> UsersNamePostResponse:
    """
    Create a new user
    """
    pass
