# generated by fastapi-codegen:
#   filename:  openapi-improved.yaml
#   timestamp: 2024-07-19T05:05:28+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, conint


class Credentials(BaseModel):
    id: str
    key: str


class Task(BaseModel):
    name: str
    description: str
    status: conint(ge=0, le=2)
    runner: str
    creator: str
    data: str = ''
    last_updated: Optional[datetime] = None
    created_date: datetime


class TaskNamePutRequest(BaseModel):
    credentials: Credentials
    data: str


class TaskPostRequest(BaseModel):
    credentials: Credentials
    name: str
    desc: str = ''
